config/routes.rb
DeviseBase::Application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  
  resources :users, :only => [ :index, :show, :edit, :update, :destroy ]

  root :to => 'statics#home'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
       user ||= User.new # guest user (not logged in)
       if user.role? :admin
         can :manage, :all
       elsif user.role? :moderator
         can :read, :all
       elsif user.role? :user
         can :read, :all
         can [ :update, :destroy ], User, :id => user.id
       else
         
       end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/role.rb
class Role < ActiveRecord::Base
  
  has_and_belongs_to_many :users
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name, :role_ids
  
  has_and_belongs_to_many :roles
  
  accepts_nested_attributes_for :roles, :allow_destroy => true
  validates :name, :email, :presence => true
  
  after_create :add_user_role
  
  def self.find_for_facebook_oauth(access_token, signed_in_resource=nil)
    data = access_token.extra.raw_info
    if user = User.where(:email => data.email).first
      user
    else # Create a user with a stub password.
      User.create!(:name => "#{data.first_name} #{data.last_name}", :email => data.email, :password => Devise.friendly_token[0,20])
    end
  end
  
  def role?(role)
    return !!self.roles.find_by_name(role.to_s.camelize)
  end
  
  private
  
    def add_user_role
      self.roles << Role.find_by_name('User')
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  protect_from_forgery
  
  check_authorization :unless => :devise_controller?
  
  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, :alert => exception.message
  end
  
end

app/controllers/statics_controller.rb
class StaticsController < ApplicationController
  
  skip_authorization_check

  def home
  end
  
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Facebook"
      sign_in_and_redirect @user, :event => :authentication
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  load_and_authorize_resource
  
  def index
    @title = 'View Users'
    @users = User.paginate(:page => params[:page])
  end

  def show
    @user = User.find(params[:id])
    @title = @user.name
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    
    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to action: 'index', notice: 'User was successfully updated.' }
      else
        format.html { render action: "edit" }
      end
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :ok }
    end
  end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  # return a title on a per-page basis
  def title
    base_title = "#{organization} #{country}"
    if @title.nil?
      base_title
    else
      "#{base_title} | #{@title}"
    end
  end
end

app/helpers/statics_helper.rb
module StaticsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_alert.html.haml
= alert

app/views/layouts/_footer.html.haml
%hr
= render 'layouts/menu'

app/views/layouts/_header.html.haml
= render 'layouts/menu'
%hr

app/views/layouts/_menu.html.haml
- if user_signed_in?
  %p
    You are signed in as
    = current_user.name
    [
    = current_user.email
    ]
    You are a(n)
    - current_user.roles.each do |role|
      |
      = role.name
    = link_to 'sign out', destroy_user_session_path, :method => :delete
    |
    = link_to 'edit your profile', edit_user_path(current_user)
    |
    = link_to 'home', root_path
    |
    = link_to 'users', users_path
- else
  %p
    Please
    = link_to 'sign in', new_user_session_path
    or
    = link_to 'sign up', new_user_registration_path
    \.

app/views/layouts/_notice.html.haml
= notice

app/views/layouts/application.html.haml
<!DOCTYPE html>
%html
  %head
    %title title
    = stylesheet_link_tag "application", :media => 'all'
    = javascript_include_tag "application"
    = csrf_meta_tags
    -#%link{:href => image_path('favicon.ico'), :type => 'image/x-icon', :rel => 'icon'}
  %body{:class => "#{params[:controller].parameterize}", :id => "#{params[:action].parameterize}"}
    = render 'layouts/header'
    = render 'layouts/notice', :notice => notice
    = render 'layouts/alert', :alert => alert
    = yield
    - if Rails.env.development?
      = debug(params)
      Class: #{params[:controller].parameterize}
      %br
      ID: #{params[:action].parameterize}
    = render 'layouts/footer'

app/views/statics/home.html.haml
%h1 Root Page

%ul
  %li= link_to 'Google', '/auth/google_oauth2'
  %li= link_to 'Twitter', '/auth/twitter'
  %li= link_to 'Github', '/auth/github'
%hr

%h2 User Roles
%p A check mark indicates you possess this role.
%ul
  - Role.all.each do |role|
    %li
      = role.name
      - if user_signed_in? && current_user.roles.find_by_name(role.name)
        &#x2713;
- if user_signed_in?
  %p Safety checks.
  %ul
    %li= 'if you can read this you can manage users' if can? :manage, User
    %li= 'if you can read this you can read users' if can? :read, User
    %li= 'if you can read this you can update users' if can? :update, User
    %li= 'if you can read this you can create users' if can? :create, User
    %li= 'if you can read this you can destroy users' if can? :destroy, User
    %li= 'if you can read this you can manage everything' if can? :manage, :all

%h1 Readme

%p The Gemfile contains both thin and foreman, and it is recommended you use thin as your client and foreman to manage it.
%p Start the server with 'foreman start'.

%p This page is located in app/views/pages/home.html.erb. Please modify it to reflect your home page.
%p This base comes with the following, all in vendor/assets:

%h4 CSS
%ul
  %li Blueprint
  %ul
    %li ie.css
    %li typography.css
    %li reset.css
  %li 1140 CSS Grid
  %ul
    %li 1140.css
    %li styles.css.scss
  %li formalize.css.scss
%hr
%h4 JS
%ul
  %li 1140 CSS Grid
  %ul
    %li css3-mediaqueries.js
  %li jquery.formalize.min.js
  %li jquery.url.js
%hr
%h4 Images
%ul
  %li Mostly complete icon set.
%hr
%p The app/assets/stylesheets/application.css loads vendor sheets, plus the default.css.scss file, into which all SASS sheets should be @imported. All SASS sheets to be imported need to begin with an underscore.
%p The app/assets/javascripts/application.js loads all .js files, as well as the jquery-ui plugin, served from rails.

%h2 Setup

%ul
  %li Set both your development and production API keys and secrets in /config/initializers/dev_environment.rb
  %li Add yourself as an admin using the console [ User.create!(:email => 'YOUR_EMAIL', :password => 'YOUR_PASSWORD') ]
  %li Start the server! [ foreman start ] It'll be available at localhost:5000

%h2 Deploying on Heroku (assumes an existing git repository)

%code
  gem install heroku
  heroku keys:add
  heroku create --stack cedar
  git checkout -b heroku
  git push heroku heroku:master
  heroku run rake db:migrate

app/views/users/_form.html.haml
= semantic_form_for @user do |f|
  = f.inputs :name
  = f.input :roles, :as => :check_boxes if can? :manage, @user
  = f.buttons

app/views/users/_user.html.haml
%h2= user.name
%p
  = user.email
  %br
  = link_to 'go to user', user
  &rang;

app/views/users/edit.html.haml
%p
  You have registered using #{@user.email}.
  = link_to 'change', edit_user_registration_path
= render 'form'
= link_to 'change your password', edit_user_registration_path

app/views/users/index.html.haml
= will_paginate
= render @users

app/views/users/show.html.haml
%h1= @user.name
%p= @user.email
%p
  = link_to 'edit', edit_user_path if can? :update, @user
  = link_to "delete account", @user, :confirm => "Are you sure?", :method => :delete if can? :destroy, @user